/**
 * RecommendationsSection Component.
 * Presents AI engineering recommendations, potential optimizations, complexity reductions,
 * alternative technology suggestions, and project risks.
 * Explicitly distinguishes user requirements from AI suggestions.
 */
export default function RecommendationsSection({
  recommendations = [],
  risks = [],
  assumptions = [],
  openQuestions = [],
}) {
  const hasContent =
    (recommendations && recommendations.length > 0) ||
    (risks && risks.length > 0) ||
    (assumptions && assumptions.length > 0) ||
    (openQuestions && openQuestions.length > 0);

  if (!hasContent) return null;

  return (
    <section className="card" aria-label="Risks and AI Recommendations">
      <div style={{ marginBottom: '1.25rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem' }}>
          <span style={{ fontSize: '1.25rem' }}>💡</span>
          <h3 style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--text-primary)', margin: 0 }}>
            Risks & AI Engineering Recommendations
          </h3>
        </div>
        <p style={{ fontSize: '0.8125rem', color: 'var(--text-secondary)', margin: 0 }}>
          Architectural advice, risk mitigations, and potential enhancements generated by IdeaStruct AI.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        {/* Implementation Risks */}
        {risks?.length > 0 && (
          <div>
            <h4 style={{ fontSize: '0.9375rem', fontWeight: 700, color: 'var(--accent-orange)', marginBottom: '0.75rem' }}>
              ⚠️ Technical & Implementation Risks ({risks.length})
            </h4>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '0.75rem' }}>
              {risks.map((risk, idx) => (
                <div
                  key={risk.id || idx}
                  style={{
                    padding: '0.85rem 1rem',
                    backgroundColor: 'rgba(245, 158, 11, 0.05)',
                    border: '1px solid rgba(245, 158, 11, 0.25)',
                    borderRadius: 'var(--radius-md)',
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.35rem' }}>
                    <strong style={{ fontSize: '0.875rem', color: 'var(--text-primary)' }}>
                      {risk.risk || `Risk #${idx + 1}`}
                    </strong>
                    {risk.severity && (
                      <span
                        style={{
                          fontSize: '0.6875rem',
                          fontWeight: 700,
                          padding: '0.1rem 0.4rem',
                          borderRadius: '3px',
                          backgroundColor:
                            risk.severity === 'HIGH'
                              ? 'rgba(239, 68, 68, 0.2)'
                              : 'rgba(245, 158, 11, 0.2)',
                          color: risk.severity === 'HIGH' ? 'var(--status-down)' : 'var(--status-warn)',
                        }}
                      >
                        {risk.severity}
                      </span>
                    )}
                  </div>
                  {risk.mitigation && (
                    <div style={{ fontSize: '0.8125rem', color: 'var(--text-secondary)', lineHeight: 1.4 }}>
                      <strong style={{ color: 'var(--accent-cyan)' }}>Mitigation:</strong> {risk.mitigation}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* AI Recommendations */}
        {recommendations?.length > 0 && (
          <div>
            <h4 style={{ fontSize: '0.9375rem', fontWeight: 700, color: 'var(--accent-cyan)', marginBottom: '0.75rem' }}>
              ✨ Engineering Suggestions & Optimizations ({recommendations.length})
            </h4>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '0.75rem' }}>
              {recommendations.map((rec, idx) => (
                <div
                  key={idx}
                  style={{
                    padding: '0.85rem 1rem',
                    backgroundColor: 'var(--bg-elevated)',
                    border: '1px solid var(--border-subtle)',
                    borderRadius: 'var(--radius-md)',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem', marginBottom: '0.35rem' }}>
                    <span style={{ fontSize: '0.875rem' }}>💡</span>
                    <strong style={{ fontSize: '0.875rem', color: 'var(--text-primary)' }}>
                      {rec.title || rec.topic || `Recommendation #${idx + 1}`}
                    </strong>
                  </div>
                  <p style={{ fontSize: '0.8125rem', color: 'var(--text-secondary)', margin: 0, lineHeight: 1.4 }}>
                    {rec.description || rec.suggestion || (typeof rec === 'string' ? rec : '')}
                  </p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Assumptions */}
        {assumptions?.length > 0 && (
          <div>
            <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
              Engineering Assumptions
            </h4>
            <ul style={{ paddingLeft: '1.25rem', margin: 0, fontSize: '0.8125rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
              {assumptions.map((assump, idx) => (
                <li key={idx} style={{ marginBottom: '0.35rem' }}>
                  {typeof assump === 'string'
                    ? assump
                    : assump.description || assump.statement || assump.reason || JSON.stringify(assump)}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Open Questions */}
        {openQuestions?.length > 0 && (
          <div>
            <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>
              Things to Clarify (Open Questions)
            </h4>
            <ul style={{ paddingLeft: '1.25rem', margin: 0, fontSize: '0.8125rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
              {openQuestions.map((q, idx) => (
                <li key={idx} style={{ marginBottom: '0.35rem' }}>
                  {typeof q === 'string'
                    ? q
                    : q.question || q.text || q.description || JSON.stringify(q)}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </section>
  );
}
